- name: coke
  price: 3
  amount: 10

- name: fanta
  price: 3
  amount: 7

- name: mate
  price: 2.5
  amount: 10

- name: water
  price: 1
  amount: 10

- name: beer
  price: 5
  amount: 10

- name: martini
  price: 9
  amount: 2

